AllCops:
  NewCops: enable
  Exclude:
    - gemfiles/**/*

Layout/LineLength:
  Max: 140
  Exclude:
    - spec/**/*

Lint/SuppressedException:
  Exclude:
    - spec/**/*

Lint/ConstantDefinitionInBlock:
  Enabled: false

Gemspec/RequiredRubyVersion:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - advanced-sneakers-activejob.gemspec
    - spec/**/*

Metrics/CyclomaticComplexity:
  Exclude:
    - spec/support/log_helpers.rb

Metrics/MethodLength:
  Exclude:
    - spec/**/*

Security/MarshalLoad:
  Exclude:
    - spec/**/*

Security/Eval:
  Exclude:
    - spec/apps/**/*

Metrics/AbcSize:
  Exclude:
    - spec/**/*

Style/Documentation:
  Enabled: false
