#!/bin/sh

set -ex

sudo apt-get install -y wget
wget -O - "https://github.com/rabbitmq/signing-keys/releases/download/2.0/rabbitmq-release-signing-key.asc" | sudo apt-key add -

sudo tee /etc/apt/sources.list.d/bintray.rabbitmq.list <<EOF
deb https://dl.bintray.com/rabbitmq-erlang/debian xenial erlang
deb https://dl.bintray.com/rabbitmq/debian xenial main
EOF

sudo apt-get update -y
sudo apt-get install -y --allow-unauthenticated rabbitmq-server

sudo systemctl start rabbitmq-server
sudo rabbitmq-plugins enable rabbitmq_management
sudo rabbitmqctl set_user_tags guest administrator

until sudo lsof -i:5672 && sudo lsof -i:15672; do echo "Waiting for RabbitMQ to start..."; sleep 1; done
