name: Main

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    container: ruby:${{ matrix.ruby }}

    services:
      rabbitmq:
        image: rabbitmq:3.8-management-alpine
        options: >-
          --health-cmd "rabbitmq-diagnostics -q listeners"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    strategy:
      matrix:
        ruby:
          - '2.7'
          - '3.0'
          - '3.1'
          - '3.2'
          - '3.3'
          - '3.4'
        gemfile:
          - gemfiles/activejob_6.0.x.gemfile
          - gemfiles/activejob_6.1.x.gemfile
          - gemfiles/activejob_7.0.x.gemfile
          - gemfiles/activejob_7.1.x.gemfile
          - gemfiles/activejob_7.2.x.gemfile
        exclude:
          # --- Rails 7.2 (Requires Ruby 3.1+) ---
          # Exclude Ruby 2.7 to 3.0
          - ruby: '2.7'
            gemfile: gemfiles/activejob_7.2.x.gemfile
          - ruby: '3.0'
            gemfile: gemfiles/activejob_7.2.x.gemfile

          # --- Rails 7.0 (Upper Bounds) ---
          # Rails 7.0 does not officially support Ruby 3.4+
          - ruby: '3.4'
            gemfile: gemfiles/activejob_7.0.x.gemfile

          # --- Rails 6.0 & 6.1 (Upper Bounds) ---
          # Rails 6.0 and 6.1 do not officially support Ruby 3.1+ (many gems break)
          - ruby: '3.1'
            gemfile: gemfiles/activejob_6.0.x.gemfile
          - ruby: '3.1'
            gemfile: gemfiles/activejob_6.1.x.gemfile
          - ruby: '3.2'
            gemfile: gemfiles/activejob_6.0.x.gemfile
          - ruby: '3.2'
            gemfile: gemfiles/activejob_6.1.x.gemfile
          - ruby: '3.3'
            gemfile: gemfiles/activejob_6.0.x.gemfile
          - ruby: '3.3'
            gemfile: gemfiles/activejob_6.1.x.gemfile
          - ruby: '3.4'
            gemfile: gemfiles/activejob_6.0.x.gemfile
          - ruby: '3.4'
            gemfile: gemfiles/activejob_6.1.x.gemfile
    steps:
    - name: Checkout code
      uses: actions/checkout@v5

    - name: Install dependencies
      env:
        BUNDLE_GEMFILE: ${{ matrix.gemfile }}
      run: |
        bundle install --jobs 4 --retry 3
    - name: Run the default task
      env:
        BUNDLE_GEMFILE: ${{ matrix.gemfile }}
        RABBITMQ_URL: amqp://guest:guest@rabbitmq/advanced_sneakers
      run: rake
